# Generated by Django 2.2 on 2020-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='hash',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Hash'),
        ),
    ]
